server:
  port: 8189
  servlet:
    context-path: /rrr
spring.datasource:
  platform: postgres
  driverClassName: org.postgresql.Driver
  driver-class-name: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/postgres?currentSchema=prodmag
  username: postgres
  password: postgres
jpa:
  show-sql: true
  properties:
  hibernate:
    current_session_context_class:thread
spring.jpa:
  database: POSTGRESQL
  hibernate.ddl-auto: 
  show-sql: true

